name: LoafThePenguin.Helpers Package Release
on: 
  push:
    branches: [release]
    paths: ['**/LoafThePenguin.Helpers/**']
    tags: 
        - "v*.*"      
  workflow_dispatch:
    branches: [release]
jobs:
  Release:
    name: Release
    runs-on: windows-latest
    env:
      PRJ: "LoafThePenguin.Helpers"
      SLN: "$env:PRJ.sln"
      SLN_PATH: "src/$env:PRJ/$env:SLN"
      PRJ_PATH: "src/$env:PRJ/src/$env:PRJ"
      PKG_PATH: "**/$env:PRJ/**/*.nupkg"
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.*.*
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"LoafThePenguin_LoafThePenguin.Packages" /o:"loafthepenguin" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url="https://sonarcloud.io"
          dotnet build $env:SLN_PATH
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
      - uses: actions/checkout@v2
        with:
          # avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          setAllVars: true
          setCommonVars: true
      - run: "echo 'SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}'"
      - name: Pack
        run: dotnet pack $env:PRJ_PATH -c Release
      - name: Publish
        run: dotnet nuget push $env:PKG_PATH --api-key ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/LoafThePenguin/index.json
