name: LoafThePenguin.Helpers Build And Check
on:
    workflow_dispatch:

    push:
        branches: [dev]
        paths: ['**/LoafThePenguin.Helpers/**']
        
    pull_request:
        branches: [dev, release]
        paths: ['**/LoafThePenguin.Helpers/**']
        types: [opened, synchronize, reopened]
jobs:
    Sonar:
        uses: ./.github/workflows/Sonar.yml
        with: 
            project: LoafThePenguin.Helpers
